name: Workflow Publisher
on:
 push:
   branches: [ 'develop',  'master', 'main' ]
   paths:
   - 'templates/**'

jobs:
  publish-workflow-template:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target_repo: [ 'musical-spork' , 'crispy-barnacle', 'cuddly-robot' ]
    steps:
      - name: Checkout Workflows
        uses: actions/checkout@v2
        with:
          path: main
      - name: Checkout target repo
        uses: actions/checkout@v2
        with:
          repository: ${{ github.repository_owner }}/${{ matrix.target_repo }}
          path: ${{ matrix.target_repo }}
          token: ${{ secrets.RW_REPO}}
          ref: main
      - name: Update workflows
        shell: bash
        run: |
          mkdir -p .github/workflows/
          cp -r ../main/templates/* .github/
        working-directory: ./${{ matrix.target_repo }}
        env:
          CI_BRANCH_NAME: ci/workflow-publisher-${{ github.sha }}
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.RW_REPO}}
          # base: main
          commit-message: "ci: workflow publisher"
          committer: "GitHub Action <action@github.com>"
          branch: ci/workflow-publisher-${{ github.sha }}
          delete-branch: false
          title: "ci: workflow publisher"
          path: ./${{ matrix.target_repo }}
      - name: Check outputs
        if: ${{ steps.cpr.outputs.pull-request-number }}
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"